name: Build and release workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Set up .NET
      uses: actions/setup-dotnet@v1
    - name: Set version variables
      uses: dotnet/nbgv@v0.4
      with:
        setAllVars: true
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test -c Release --no-build
    - name: Pack NuGet
      run: dotnet pack -c Release --no-build --output dist
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: nupkg
        path: dist
