name: Build and release workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Set up .NET
      uses: actions/setup-dotnet@v1
    - name: Set version variables
      uses: dotnet/nbgv@v0.4
      with:
        setAllVars: true
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test -c Release --no-build
    - name: Pack NuGet
      run: dotnet pack -c Release --no-build --output dist
    - name: Publish NuGet
      env:
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
      run: dotnet nuget push dist/*.nupkg -k ${NUGET_KEY} --skip-duplicate --no-symbols
